// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/clases-layouts/CardGrid.tsx": () => import("../components/mockups/clases-layouts/CardGrid.tsx"),
  "./components/mockups/clases-layouts/KanbanLevels.tsx": () => import("../components/mockups/clases-layouts/KanbanLevels.tsx"),
  "./components/mockups/clases-layouts/ScheduleStrips.tsx": () => import("../components/mockups/clases-layouts/ScheduleStrips.tsx")
};
